//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMag
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Subjects
    {
        public int SubjectID { get; set; }
        public string Subject { get; set; }
        public string LeadTeacher { get; set; }
        public string SubTeacher { get; set; }
        public string ClassYear { get; set; }
    }
}
